# Generated by Django 5.0.4 on 2024-04-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0002_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Goods',
        ),
    ]
