# Generated by Django 5.0.4 on 2024-05-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0008_news_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='test',
        ),
    ]
