# Generated by Django 5.0.4 on 2024-05-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0009_remove_news_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
