# Generated by Django 5.0.4 on 2024-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0011_alter_news_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
